### ISSUE TITLE
Waste of time

### ISSUE THREAD

**Issue by tom-lord** [ruby-lint/ruby_lint#13]
This is not productive. Frankly, it's embarrassing.

**Comment by listrophy** [comment]
Thank you for sharing your feelings, @tom-lord . However, OSS authors may spend their time as they please.

**Comment by tom-lord** [comment]
Oh, sure. You can do as you please.

But I'd be far less inclined to hire someone if I saw nonsense like this in their open source "contributions".

**Comment by listrophy** [comment]
Thank you again for sharing your feelings on this. Since they don’t seem to have an actionable outcome for this project, would you care to close this issue?

**Comment by tom-lord** [comment]
An actionable outcome would be to delete the project.

I think it's entirely counter-productive to expend any effort into this rename, which is based purely on the premise that "cops are bad".

I will let the author of this fork decide whether to listen to the community (such as myself) telling them that this project should be abandoned, or to close this issue and proceed with all the renaming.

**Comment by suvratapte** [comment]
Oh no! I know a criminal with the surname "Lint". I feel very uncomfortable using the name. Will you please change it to something else?

**Comment by tom-lord** [comment]
I find it highly offensive to [name this project after a pro-Kremlin political activist, arrested on charges of organising mass riots](https://en.wikipedia.org/wiki/Dmitri_Linter).

**Comment by listrophy** [comment]
Tom, you’re being a troll. You too Suvrat. If you’re going to criticize, please do so in a reasonable and non-inflammatory manner.

**Comment by tom-lord** [comment]
@listrophy Okay okay, sorry.. that's fair.. but joking aside, the reasons why I think you should not work on this project rename are:

1. The effort required to perform a full rename of all references to "cop" is this project - and all of its third party dependencies - is huge.
2. Should this project gain traction, the ruby community's confusion around having a completely new name for the same project will be significant. Particularly if there are _multiple_ competing renames, or the feature set of this fork goes out-of-sync with the original project.
3. The motivation behind this change, i.e. "cops are bad" isn't even something I'd even like to support.

This is very different to the renaming of `FactoryGirl` --> `FactoryBot`, because:

1. The effort required to update the project and its dependencies was fairly trivial, for all people involved.
2. The original project was renamed, rather than a competing fork being created. Additionally, the new name is close to the original; thus minimising confusion.
3. So for example, I don't really mind the renaming of "FactoryGirl" --> "FactoryBot" because it was a fairly painless migration.
4. I can appreciate how some people might take offence to the name, interpreting it as somehow sexist. It was actually an obscure reference to [a Rolling Stones song](https://en.wikipedia.org/wiki/Factory_Girl_%28The_Rolling_Stones_song%29), but that's a moot point.

As I said before, you're free to write whatever software you like. But in my opinion, due to the points above, the mere existence of this fork is counter-productive.

**Comment by listrophy** [comment]
Thank you @tom-lord .

Have read the top of the README on this project lately? I don’t think it addresses all of your points, but I just want to make sure you’re aware of the logistical intent of this project.

**Comment by tom-lord** [comment]
@listrophy The author of rubocop has already rejected renaming it, and the majority of the ruby community thus far have agreed with this opinion. So if the "success" of this fork depends on being merged into the original, then I think it's doomed for failure.

Besides, merging this rename into `rubocop`'s master branch on _partially_ addresses issue 2 I raised above. I would still consider this work counter productive for the other reasons I listed.

**Comment by waltercool** [comment]
The name of this project is quite offensive, would you change it for something more neutral?

A proposal I can do could be Robocop, a guy who was a cop, but faced corrupt cops. After all, this tool guards your code from corrupt developers who don't code properly.
