### ISSUE TITLE
Code of conduct?

### ISSUE THREAD

**Issue by CoralineAda** [ruby-lint/ruby_lint#2]

**Comment by listrophy** [comment]
I’m guessing @CoralineAda didn’t prime this thread with a link to https://www.contributor-covenant.org/ so as to avoid the appearance of bias (seeing a she’s the author), but I’m happy to suggest its use!

**Comment by veganstraightedge** [comment]
Yes! @CoralineAda 👍🏻

I only got as far as forking and renaming the repo when I tweeted it.

**Comment by CoralineAda** [comment]
Just a friendly nudge. Let me know how I can help. You’re doing a good thing here.
