### ISSUE TITLE
Remove this repo

### ISSUE THREAD

**Issue by DaniruKun** [ruby-lint/ruby_lint#21]
Unnecessary fork of Rubocop that achieves nothing.

**Comment by 1vasari** [comment]
I think given the recent exposé of police behaviour it is a reasonable and considerate response to a sensitive issue. A rose by any other name would be just as sweet, as they say..

**Comment by waltercool** [comment]
Why USA people thinks everything it happens at their country should affect everyone else at the world?

Stop being that, seriously, this is why Europeans, Asians and LatinoAmericans hates US people
